name: DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:staging \
                       -t ghcr.io/${{ github.repository }}:${{ github.run_id }} \
                       -f DevOpsWebApplication/Dockerfile .
          docker push ghcr.io/${{ github.repository }} --all-tags

      - name: Create release notes
        id: semver-app
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.semver-app.outputs.version }}
          generateReleaseNotes: true
          body: |
            This release includes the following container image:
            http://ghcr.io/${{ github.repository }}:${{ steps.semver-app.outputs.version }}
            
      - name: Application Version
        id: semver-app
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: true
          
      - name: Display Version
        run: echo "Generated version is ${{ steps.semver-app.outputs.version }}"